### PR TITLE
258 end of year bug

### LINKED ISSUE #258: Fix end of year bug
Jeg har funnet en løsning, som ikke er så pen, men er basert på koden i #257

### PR DESCRIPTION
**Pull request by sigtheidiot**
Closes #258

### CODE REVIEW

File: backend/Core/DomainModels/Week.cs [hunk 1]
```diff
@@ -33,11 +33,14 @@ public bool Equals(Week? other)
...
     {
+        if (WeekNumber < 10) return $"{Year}0{WeekNumber}";
         return $"{Year}{WeekNumber}";
     }
 
     public int ToSortableInt()
     {
+        if (WeekNumber < 10) return int.Parse(($"{Year}0{WeekNumber}"));
+
         return int.Parse($"{Year}{WeekNumber}");
```
Comment (jonasbjoralt) [inline backend/Core/DomainModels/Week.cs:44]:
```suggestion
 return (Year * 100) + WeekNumber
```

File: backend/Core/DomainModels/Week.cs [hunk 2]
```diff
@@ -33,11 +33,14 @@ public bool Equals(Week? other)
 
     public override string ToString()
     {
+        if (WeekNumber < 10) return $"{Year}0{WeekNumber}";
         return $"{Year}{WeekNumber}";
```
Comment (jonasbjoralt) [inline backend/Core/DomainModels/Week.cs:37]: return $"{ToSortableInt()}"

**Review by jonasbjoralt — APPROVED** [review]
Nice!
